import type { Metadata } from "next";
import { Inter, Saira_Stencil_One } from "next/font/google";
import BackgroundCity from "./shared/components/backgroundCity";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const saira = Saira_Stencil_One({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${saira.className} bg-[#05253E]`}>
        <BackgroundCity />
        {children}
      </body>
    </html>
  );
}
